apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t13l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t13l
    app.kubernetes.io/part-of: basic-go-sample
  name: devfile-sample-t13l
  namespace: ktsao-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-t13l
status:
  loadBalancer: {}
