apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pnai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pnai
    app.kubernetes.io/part-of: basic-go-sample
  name: devfile-sample-pnai
  namespace: ktsao-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-pnai
    weight: null
status: {}
